# Homework 2: Arrays and Tables, Due Sunday, October 15, at 11:59pm

**Reading**: Textbook chapters [4](http://www.inferentialthinking.com/chapters/04/data-types.html) and [5](http://www.inferentialthinking.com/chapters/05/tables.html).

Deadline:

This assignment is due Sunday, October 15, at 11:59pm. You are given two slip days thoughout the quarter which can extend the deadline by one day. See the syllabus for more details. With the exception of using slip days, late work will not be accepted. 

Directly sharing answers is not okay, but discussing problems with the course staff or with other students is encouraged. 

You should start early so that you have time to get help if you're stuck. A calendar with lab hour times and locations appears on (https://sites.google.com/a/eng.ucsd.edu/dsc10-fall-2017/staff-hours).

Please complete this notebook by filling in the cells provided. Before you begin, execute the following cell to load the provided tests. Each time you start your server, you will need to execute this cell again to load the tests.

In [3]:
# Don't change this cell; just run it. 

import numpy as np
from datascience import *

from client.api.notebook import Notebook
ok = Notebook('hw02.ok')
_ = ok.auth(inline=True)

Assignment: Homework 2: Arrays and Tables
OK, version v1.12.8


Open the following URL:

https://okpy.org/client/login/

After logging in, copy the code from the web page and paste it into the box.
Then press the "Enter" key on your keyboard.



KeyboardInterrupt: 

**Important**: The `ok` tests don't always tell you that your answer is correct. More often, they help catch careless mistakes. It's up to you to ensure that your answer is correct. If you're not sure, ask someone (not for the answer, but for some guidance about your approach).

Once you're finished, select "Save and Checkpoint" in the File menu and then execute the `submit` cell below. The result will contain a link that you can use to check that your assignment has been submitted successfully. If you submit more than once before the deadline, we will only grade your final submission.

In [3]:
_ = ok.submit()

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Saving notebook... Saved 'hw02.ipynb'.
Submit... 100% complete
Submission successful for user: gul002@ucsd.edu
URL: https://okpy.org/ucsd/dsc10/fa17/hw02/submissions/31LLn9



## 1. Studying the Survivors


The Reverend Henry Whitehead was skeptical of John Snow’s conclusion about the Broad Street pump. After the Broad Street cholera epidemic ended, Whitehead set about trying to prove Snow wrong.  (The history of the event is detailed [here](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1034367/pdf/medhist00183-0026.pdf).)

He realized that Snow had focused his analysis almost entirely on those who had died. Whitehead, therefore, investigated the drinking habits of people in the Broad Street area who had not died in the outbreak.

What is the main reason it was important to study this group?

1) If Whitehead had found that many people had drunk water from the Broad Street pump and not caught cholera, that would have been evidence against Snow's hypothesis.

2) Survivors could provide additional information about what else could have caused the cholera, potentially unearthing another cause.

3) Through considering the survivors, Whitehead could have identified a cure for cholera.

In [15]:
# Set survivor_answer to 1, 2, or 3
survivor_answer = 1

In [16]:
_ = ok.grade('q1_1')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



**Note:** Whitehead ended up finding further proof that the Broad Street pump played the central role in spreading the disease to the people who lived near it. Eventually, he became one of Snow’s greatest defenders.

## 2. Creating Arrays


**Question 1.** Make an array called `weird_numbers` containing the following numbers (in the given order):

1. -2
2. the sine of 1.2
3. 3
4. 5 to the power of the cosine of 1.2

*Hint:* `sin` and `cos` are functions in the `math` module.

In [23]:
# Our solution involved one extra line of code before creating
# weird_numbers.
import math
weird_numbers =make_array([-2,math.sin(1.2),3,5**math.cos(1.2)])
weird_numbers

array([[-2.        ,  0.93203909,  3.        ,  1.79174913]])

In [24]:
_ = ok.grade('q2_1')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



**Question 2.** Make an array called `numbers` containing the following three strings: "one", "two", and "and three".

In [25]:
numbers = make_array(["Eats", "Shoots", "and Leaves"])
numbers

array([['Eats', 'Shoots', 'and Leaves']],
      dtype='<U10')

In [26]:
_ = ok.grade('q2_2')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



Strings have a method called `join`.  `join` takes one argument, an array of strings.  It returns a single string.  Specifically, the value of `a_string.join(an_array)` is a single string that's the [concatenation](https://en.wikipedia.org/wiki/Concatenation) ("putting together") of all the strings in `an_array`, **except** `a_string` is inserted in between each string

**Question 3.** Use the array `numbers` and the method `join` to make two strings:

1. "one, two, and three" (call this one `with_commas`)
2. "one two and three" (call this one `without_commas`)

*Hint:* If you're not sure what `join` does, first try just calling, for example, `"foo".join(numbers)` .

In [35]:
with_commas = ",".join(["one", "two", "three"])
without_commas = " ".join(["one", "two", "three"])

# These lines are provided just to print out your answers.
print('with_commas:', with_commas)
print('without_commas:', without_commas)

with_commas: one,two,three
without_commas: one two three


In [36]:
_ = ok.grade('q2_3')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



## 3. Indexing Arrays


These exercises give you practice accessing individual elements of arrays.  In Python (and in many programming languages), elements are accessed by *index*, so the first element is the element at index 0.  

**Question 1.** The cell below creates an array of some numbers.  Set `second_element` to the second element of `some_numbers`.

In [13]:
some_numbers = make_array(-1, -3, -6, -10, -15)

second_element = some_numbers[1]
second_element

-3

In [14]:
_ = ok.grade('q3_1')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



**Question 2.** The next cell creates a table that displays some information about the elements of `some_numbers` and their order.  Run the cell to see the partially-completed table, then fill in the missing information in the cell (the strings that are currently "???") to complete the table.

In [37]:
elements_of_some_numbers = Table().with_columns(
    "English name for position", make_array("first", "second", "third", "forth", "fifth"),
    "Index",                     make_array("0", "1", "2", "3", "4"),
    "Element",                   some_numbers)
elements_of_some_numbers

English name for position | Index | Element
first                     | 0     | -1
second                    | 1     | -3
third                     | 2     | -6
forth                     | 3     | -10
fifth                     | 4     | -15

In [38]:
_ = ok.grade('q3_2')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



**Question 3.** You'll sometimes want to find the *last* element of an array.  Suppose an array has 106 elements.  What is the index of its last element?

In [39]:
index_of_last_element = 105

In [40]:
_ = ok.grade('q3_3')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



The following cell loads data about presidents into a table and prints out the data. 

In [41]:
president_data = Table.read_table("president_births.csv")
president_data

Name                   | Birth      | Death      | Birth Year | Birth Days (since 1 CE) | Days since January 1 at Birth | Death Year | Death Days (since 1 CE) | Days since January 1 at Death | Life Years | Life Days
George Washington      | 1732-02-22 | 1799-12-14 | 1732       | 632286                  | 53                            | 1799       | 657053                  | 348                           | 67         | 24767
John Adams             | 1735-10-30 | 1826-07-04 | 1735       | 633632                  | 303                           | 1826       | 666751                  | 185                           | 90         | 33119
Thomas Jefferson       | 1743-04-13 | 1826-07-04 | 1743       | 636354                  | 103                           | 1826       | 666751                  | 185                           | 83         | 30397
James Madison          | 1751-03-16 | 1836-06-28 | 1751       | 639248                  | 75                            | 1836       | 670398                  | 180                           | 85         | 31150
James Monroe           | 1758-04-28 | 1831-07-04 | 1758       | 641848                  | 118                           | 1831       | 668577                  | 185                           | 73         | 26729
Andrew Jackson         | 1767-03-15 | 1845-06-08 | 1767       | 645091                  | 74                            | 1845       | 673665                  | 159                           | 78         | 28574
John Quincy Adams      | 1767-07-11 | 1848-02-23 | 1767       | 645209                  | 192                           | 1848       | 674655                  | 54                            | 80         | 29446
William Henry Harrison | 1773-02-09 | 1841-04-04 | 1773       | 647249                  | 40                            | 1841       | 672139                  | 94                            | 68         | 24890
Martin Van Buren       | 1782-12-05 | 1862-07-24 | 1782       | 650835                  | 339                           | 1862       | 679920                  | 205                           | 79         | 29085
Zachary Taylor         | 1784-11-24 | 1850-07-09 | 1784       | 651555                  | 329                           | 1850       | 675522                  | 190                           | 65         | 23967
... (28 rows omitted)

More often, you don't know the number of elements in an array, its *length*.  (For example, it might be a large dataset you found on the Internet.)  The function `len` takes a single argument, an array, and returns the `len`gth of that array (an integer).

**Question 4.** The cell below loads an array called `president_death_years`. Assign the middle element of death year to `death_year`. 

**Note:** The middle element of an array of 7 elements is at index 3. The middle element of an array of 8 elements is at index 3.

In [57]:
president_death_years = Table.read_table("president_births.csv").column('Death Year')
mid = round(len(president_death_years)/2)-1
death_year = int(president_death_years[mid])
death_year

1893

In [59]:
_ = ok.grade('q3_4')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



## 4. Basic Array Arithmetic


**Question 1.** Multiply the numbers 42, 2387, 42422424, and -100 by 109.  For this question, **don't** use arrays.

In [60]:
first_product = 42*109
second_product = 2387*109
third_product = 42422424*109
fourth_product =  -100*109
print(first_product, second_product, third_product, fourth_product)

4578 260183 4624044216 -10900


In [61]:
_ = ok.grade('q4_1')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



**Question 2.** Now, do the same calculation, but using an array called `numbers` and only a single multiplication (`*`) operator.  Store the 4 results in an array named `products`.

In [72]:
numbers = make_array(42,2387,42422424,-100)
products = 109*numbers
products

array([      4578,     260183, 4624044216,     -10900])

In [73]:
_ = ok.grade('q4_2')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



**Question 3.** Oops, we made a typo!  Instead of 109, we wanted to multiply each number by 1091.  Compute the fixed products in the cell below using array arithmetic.  Notice that your job is really easy if you previously defined an array containing the 4 numbers.

In [74]:
fixed_products = 1091*numbers
fixed_products

array([      45822,     2604217, 46282864584,     -109100])

In [75]:
_ = ok.grade('q4_3')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



**Question 4.** We've loaded an array of the Body Weights of cats in the next cell.  Convert them all to ounces (1Kg has 35.274 ounces). Round each result to the nearest integer using the `round` function.

In [82]:
body_weight = Table.read_table("cats.csv").column("Body_weigh(in kg)")
body_weight_ounces = 35.274*body_weight
body_weight_ounces

array([  70.548 ,   70.548 ,   70.548 ,   74.0754,   74.0754,   74.0754,
         74.0754,   74.0754,   74.0754,   74.0754,   74.0754,   74.0754,
         77.6028,   77.6028,   77.6028,   77.6028,   77.6028,   77.6028,
         81.1302,   81.1302,   81.1302,   81.1302,   81.1302,   81.1302,
         81.1302,   81.1302,   81.1302,   81.1302,   81.1302,   81.1302,
         84.6576,   84.6576,   84.6576,   84.6576,   88.185 ,   88.185 ,
         91.7124,   91.7124,   91.7124,   95.2398,   95.2398,   95.2398,
        102.2946,  102.2946,  102.2946,  105.822 ,  105.822 ,   70.548 ,
         70.548 ,   74.0754,   77.6028,   77.6028,   77.6028,   77.6028,
         77.6028,   77.6028,   77.6028,   77.6028,   81.1302,   84.6576,
         84.6576,   84.6576,   84.6576,   84.6576,   88.185 ,   88.185 ,
         88.185 ,   88.185 ,   88.185 ,   88.185 ,   88.185 ,   88.185 ,
         91.7124,   91.7124,   91.7124,   91.7124,   91.7124,   91.7124,
         95.2398,   95.2398,   95.2398,   95.2398, 

In [83]:
_ = ok.grade('q4_4')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



**Question 5.** The cell below loads the Heart weight of all cats.  Compute the weight of each cat exluding the heart and give answer in ounces.

In [94]:
heart_weight = Table.read_table("cats.csv").column("Heart_weight(in g)")
heart_weight_ounces = 35.274*heart_weight/1000
weight_heartless_cats =body_weight_ounces-heart_weight_ounces
weight_heartless_cats

array([  70.301082 ,   70.2869724,   70.212897 ,   73.8214272,
         73.8178998,   73.8073176,   73.7896806,   73.7861532,
         73.7826258,   73.775571 ,   73.7685162,   73.7297148,
         77.3523546,   77.2959162,   77.2818066,   77.2606422,
         77.2183134,   77.214786 ,   80.8726998,   80.8515354,
         80.8338984,   80.812734 ,   80.812734 ,   80.795097 ,
         80.7915696,   80.7880422,   80.7739326,   80.7739326,
         80.7562956,   80.7351312,   84.4353738,   84.3507162,
         84.3471888,   84.2978052,   87.867534 ,   87.8005134,
         91.4055162,   91.3561326,   91.3561326,   94.939971 ,
         94.8800052,   94.8588408,  101.9453874,  101.9383326,
        101.9383326,  105.4480956,  105.363438 ,   70.318719 ,
         70.318719 ,   73.7191326,   77.3488272,   77.3347176,
         77.3241354,   77.302971 ,   77.2818066,   77.2641696,
         77.2641696,   77.2253682,   80.7915696,   84.4000998,
         84.3789354,   84.3789354,   84.3366066,   84.3

In [95]:
_ = ok.grade('q4_5')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



## 5. Old Faithful


Old Faithful is a geyser in Yellowstone that erupts every 44 to 125 minutes (according to [Wikipedia](https://en.wikipedia.org/wiki/Old_Faithful)). People are [often told that the geyser erupts every hour](http://yellowstone.net/geysers/old-faithful/), but in fact the waiting time between eruptions is more variable. Let's take a look.

**Question 1.** The first line below assigns `waiting_times` to an array of 272 consecutive waiting times between eruptions, taken from a classic 1938 dataset. Assign the names `shortest`, `longest`, and `average` so that the `print` statement is correct.

In [96]:
waiting_times = Table.read_table('old_faithful.csv').column('waiting')

shortest = 44
longest = 125
average = np.sum(waiting_times)/len(waiting_times)

print("Old Faithful erupts every", shortest, "to", longest, "minutes and every", average, "minutes on average.")

Old Faithful erupts every 44 to 125 minutes and every 70.8970588235 minutes on average.


In [97]:
_ = ok.grade('q5_1')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 3
    Failed: 0
[ooooooooook] 100.0% passed



**Question 2.** Assign `biggest_decrease` to the biggest descrease in waiting time between two consecutive eruptions. For example, the third eruption occurred after 74 minutes and the fourth after 62 minutes, so the decrease in waiting time was 74 - 62 = 12 minutes. *Hint*: You'll need an array arithmetic function [mentioned in the textbook](https://www.inferentialthinking.com/chapters/04/4/arrays.html#Functions-on-Arrays).

In [118]:
decrease = np.sort(np.diff(waiting_times))
biggest_decrease= abs (decrease[0])
biggest_decrease

45

In [119]:
_ = ok.grade('q5_2')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



**Question 3.** If you expected Old Faithful to erupt every hour, you would expect to wait a total of `60 * k` minutes to see `k` eruptions. Set `difference_from_expected` to an array with 272 elements, where the element at index `i` is the absolute difference between the expected and actual total amount of waiting time to see the first `i+1` eruptions.  *Hint*: You'll need to compare a cumulative sum to a range.

For example, since the first three waiting times are 79, 54, and 74, the total waiting time for 3 eruptions is 79 + 54 + 74 = 207. The expected waiting time for 3 eruptions is 60 * 3 = 180. Therefore, `difference_from_expected.item(2)` should be $|207 - 180| = 27$.

In [128]:
accu_waiting_time = np.cumsum(waiting_times)
expected_time = np.arange(60,60*(len(waiting_times)+1),60)
difference_from_expected = abs(accu_waiting_time-expected_time)
difference_from_expected

array([  19,   13,   27,   29,   54,   49,   77,  102,   93,  118,  112,
        136,  154,  141,  164,  156,  158,  182,  174,  193,  184,  171,
        189,  198,  212,  235,  230,  246,  264,  283,  296,  313,  319,
        339,  353,  345,  333,  353,  352,  382,  402,  400,  424,  422,
        435,  458,  462,  455,  477,  476,  491,  521,  515,  535,  529,
        552,  563,  567,  584,  605,  604,  628,  616,  638,  638,  670,
        688,  706,  711,  724,  746,  742,  761,  772,  774,  790,  790,
        808,  824,  847,  862,  884,  894,  899,  912,  940,  956,  976,
        964,  990,  990, 1020, 1010, 1028, 1031, 1043, 1067, 1082, 1073,
       1095, 1097, 1125, 1114, 1137, 1158, 1145, 1169, 1161, 1187, 1208,
       1223, 1222, 1251, 1270, 1269, 1290, 1280, 1305, 1304, 1331, 1324,
       1333, 1350, 1346, 1374, 1395, 1380, 1402, 1397, 1427, 1412, 1435,
       1431, 1460, 1446, 1468, 1459, 1485, 1478, 1497, 1518, 1518, 1540,
       1557, 1573, 1572, 1592, 1581, 1617, 1610, 16

In [129]:
_ = ok.grade('q5_3')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



**Question 4.** If instead you guess that each waiting time will be the same as the previous waiting time, how many minutes would your guess differ from the actual time, averaging over every wait time except the first one.

For example, since the first three waiting times are 79, 54, and 74, the average difference between your guess and the actual time for just the second and third eruption would be $\frac{|79-54|+ |54-74|}{2} = 22.5$.

In [134]:
diff=abs(np.diff(waiting_times))
accu_diff = np.cumsum(diff)
average_error = accu_diff[len(accu_diff)-1]/len(accu_diff)
average_error

20.520295202952031

In [135]:
_ = ok.grade('q5_4')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



## 6. Tables


**Question 1.** Suppose you have 4 apples, 3 oranges, and 3 pineapples.  (Perhaps you're using Python to solve a high school Algebra problem.)  Create a table that contains this information.  It should have two columns: "fruit name" and "count".  Give it the name `fruits`.

**Note:** Use lower-case and singular words for the name of each fruit, like `"apple"`.

In [136]:
# Our solution uses 1 statement split over 3 lines.
fruits = Table().with_columns(
    'fruit name', make_array( "apples","oranges", "pineapples"),
    'count', make_array(4, 3,3)
)
fruits

fruit name | count
apples     | 4
oranges    | 3
pineapples | 3

In [137]:
_ = ok.grade('q6_1')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



**Question 2.** The file `inventory.csv` contains information about the inventory at a fruit stand.  Each row represents the contents of one box of fruit.  Load it as a table named `inventory`.

In [5]:
inventory = Table.read_table('inventory.csv')
inventory

box ID | fruit name | count
53686  | kiwi       | 45
57181  | strawberry | 123
25274  | apple      | 20
48800  | orange     | 35
26187  | strawberry | 255
57930  | grape      | 517
52357  | strawberry | 102
43566  | peach      | 40

In [141]:
_ = ok.grade('q6_2')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



**Question 3.** Does each box at the fruit stand contain a different fruit?

In [144]:
# Set all_different to "Yes" if each box contains a different fruit or to "No" if multiple boxes contain the same fruit
all_different = "No"
all_different

'No'

In [145]:
_ = ok.grade('q6_3')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



**Question 4.** The file `sales.csv` contains the number of fruit sold from each box last Saturday.  It has an extra column called "price per fruit (\$)" that's the price *per item of fruit* for fruit in that box.  The rows are in the same order as the `inventory` table.  Load these data into a table called `sales`.

In [7]:
sales = Table.read_table('sales.csv')
sales

box ID | fruit name | count sold | price per fruit ($)
53686  | kiwi       | 3          | 0.5
57181  | strawberry | 101        | 0.2
25274  | apple      | 0          | 0.8
48800  | orange     | 35         | 0.6
26187  | strawberry | 25         | 0.15
57930  | grape      | 355        | 0.06
52357  | strawberry | 102        | 0.25
43566  | peach      | 17         | 0.8

In [147]:
_ = ok.grade('q6_4')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



**Question 5.** How many fruits did the store sell in total on that day?

In [152]:
total_fruits_sold = np.sum(sales.column("count sold"))
total_fruits_sold

638

In [153]:
_ = ok.grade('q6_5')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



**Question 6.** What was the store's total revenue (the total price of all fruits sold) on that day?

*Hint:* If you're stuck, think first about how you would compute the total revenue from just the grape sales.

In [154]:
revenue = np.multiply(sales.column("count sold"),sales.column("price per fruit ($)"))
total_revenue = np.sum(revenue)
total_revenue

106.85000000000001

In [155]:
_ = ok.grade('q6_6')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



**Question 7.** Make a new table called `remaining_inventory`.  It should have the same rows and columns as `inventory`, except that the amount of fruit sold from each box should be subtracted from that box's count, so that the "count" is the amount of fruit remaining after Saturday.

In [13]:
remaining_inventory = Table.read_table('inventory.csv')
for i in range(0,inventory.num_rows):
    remaining_inventory.column('count')[i] = remaining_inventory.column('count')[i]-sales.column('count sold')[i]
remaining_inventory

box ID | fruit name | count
53686  | kiwi       | 42
57181  | strawberry | 22
25274  | apple      | 20
48800  | orange     | 0
26187  | strawberry | 230
57930  | grape      | 162
52357  | strawberry | 0
43566  | peach      | 23

In [14]:
_ = ok.grade('q6_7')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed

